### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by vincentthefox** [Antyfly/Hotel2.0#2]

**Comment by Antyfly** [comment]
какие-то проблемы???

**Comment by VincentTheFox** [comment]
Да так, скучаю

**Comment by Antyfly** [comment]
С этим ничего поделать не могу...

**Comment by VincentTheFox** [comment]
> С этим ничего поделать не могу...
> 

Kekw, тебе рил не впадлу отвечать?)

**Comment by Antyfly** [comment]
Эм... В выходные нет...

**Comment by VincentTheFox** [comment]
> Эм... В выходные нет...
> 

Круто) Очень рад за тебя

**Comment by Antyfly** [comment]
Если бы не почта, это бы висело не прочитанным....

**Comment by VincentTheFox** [comment]
> Если бы не почта, это бы висело не прочитанным....
> 

Перввй иссью висел 3 месяца открытым, вроде) А тут ты как-то быстро ответила)

**Comment by Antyfly** [comment]
почта на работе понадобилась...

**Comment by VincentTheFox** [comment]
> почта на работе понадобилась...

:D Рад что ты нашла работу, особенно если она тебе по душе)

**Comment by Antyfly** [comment]
> > почта на работе понадобилась...
> 
> :D Рад что ты нашла работу, особенно если она тебе по душе)

Смешно

**Comment by VincentTheFox** [comment]
> > > почта на работе понадобилась...
> > 
> > :D Рад что ты нашла работу, особенно если она тебе по душе)
> 
> Смешно

Где я смеюсь? Нашла работу? Круто! Платят? Вообще заебись)

**Comment by Antyfly** [comment]
Смешно то, что ты рад за человека, который конченная сука. Так ты меня называл???

**Comment by VincentTheFox** [comment]
> Смешно то, что ты рад за человека, который конченная сука. Так ты меня называл???
> 

Мы вроде объяснились тогда по этому поводу? В итоге же это ты меня закинула в чс, в не я. Зачем опять устраивать срач? Хочешь продолжить? Пиши в тг

**Comment by Antyfly** [comment]
Смешно... Тя и не было в чс... Я не истеричка, чтобы так делать, и чаще всего если человек туда попадает, он оттуда и не выходит...

**Comment by VincentTheFox** [comment]
> Смешно... Тя и не было в чс... Я не истеричка, чтобы так делать, и чаще всего если человек туда попадает, он оттуда и не выходит...

Пиздец) Как же вы с владом заебали) Этот меня на вручении дипломов истеричкой назвал, теперь ты. Нет, это правда, но что я мог тогда с этим сделать? Чел, ты что сейчас от меня хочешь? Ты продолжаешь отвечать мне, хотя адекватный человек уже забил бы)

**Comment by Antyfly** [comment]
Во-первых, я не называла тебя истеричкой. Это уже твои проблемы, что принимаешь на свой счет эти слова. Во-вторых, ты не думаешь, что я отвечаю только из-за того, что мне скучно???

**Comment by VincentTheFox** [comment]
> Во-первых, я не называла тебя истеричкой. Это уже твои проблемы, что принимаешь на свой счет эти слова. Во-вторых, ты не думаешь, что я отвечаю только из-за того, что мне скучно???

Так, хватит. Я не хочу чтобы это превращалось в срач.

**Comment by Antyfly** [comment]
Срач???

**Comment by Antyfly** [comment]
Где ты его увидел???

**Comment by VincentTheFox** [comment]
> Срач???

А на что это похоже? Мы как две собаки, которым скучно от безделья грызёмся.

**Comment by Antyfly** [comment]
Обычная переписка...

**Comment by VincentTheFox** [comment]
> Обычная переписка...

Ладно, ок) У меня сегодня хорошее настроение, так что я не хочу кусаться

**Comment by Antyfly** [comment]
Ооо как

**Comment by VincentTheFox** [comment]
> Ооо как

Да, прикинь, бывает такое)

**Comment by VincentTheFox** [comment]
> Ооо как

А у тебя как жизнь?

**Comment by Antyfly** [comment]
Удивительно...

**Comment by Antyfly** [comment]
Удалять сообщения... Неплохо...

**Comment by vincentthefox** [comment]
> Удалять сообщения... Неплохо...

Какбэ и что?) pepegasad

**Comment by Antyfly** [comment]
Nothing

**Comment by vincentthefox** [comment]
> Nothing
> 

;) Хорошего дня
